
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace Typhoon.ServerGT
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions
        Gadgeteer.Modules.LoveElectronics.Relay relay;
        Gadgeteer.Modules.LoveElectronics.LedArray ledArray;
        Gadgeteer.Modules.LoveElectronics.USBDCPower power;
        Gadgeteer.Modules.LoveElectronics.Button button;
        Gadgeteer.Modules.LoveElectronics.Button button1;
        Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        Gadgeteer.Modules.GHIElectronics.PulseInOut pulseInOut;
        Gadgeteer.Modules.LoveElectronics.PHTemp pHTemp;
        Gadgeteer.Modules.Seeed.MoistureSensor moistureSensor;
        Gadgeteer.Modules.GHIElectronics.MotorControllerL298 motorControllerL298;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new LoveElectronics.Gadgeteer.ArgonR1();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            relay = new GTM.LoveElectronics.Relay(5);
		
            power = new GTM.LoveElectronics.USBDCPower(6);

        }
    }
}
